import random
from pathlib import Path


def gen_element():
    #  key <- an integer that is drawn uniformly at random from the range [0,10^7]
    # Return key as the generated element.
    return random.randrange(0, 10**7 + 1)


def gen_push():
    # is a push operation of an element in the form of (1, key), where 1 indicates that this operation is a push, 
    # and key is the element to be pushed.
    # Its detailed steps are:
    # - x <- a new element of key generated by invoking gen_element()
    # - return (1, x), a push for element x

    # Generate a new random key
    x = gen_element()
    # 1 means PUSH 
    return (1, x)


def gen_pop():
    # is a pop operation in the form of (2), where 2 indicates that this operation is a pop.
    # Return 2, a pop operation 
    # 2 means POP
    return 2


def gen_getTop():
    # is a getTop operation in the form of (3), where 3 indicates that this operation is a getTop.
    # Its detailed steps are:
    # Return 3, a getTop operation.
    # 3 means GET TOP
    return 3


# write data to file - creates an 'experiments' dir if required
def write_to_file(filename: str, data: list[str], base_dir: Path = Path.cwd() / "experiments"):
    path = base_dir / filename
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as file:
        file.writelines(f"{line}\n" for line in data)